export function cacheElements() {
    return {
        deviceColumn: document.getElementById("deviceColumn"),
        deviceList: document.getElementById("deviceList"),
        deviceListLimit: document.getElementById("deviceListLimit"),
        deviceListSearch: document.getElementById("deviceListSearch"),
        deviceListPagination: document.getElementById("deviceListPagination"),
        deviceListPaginationSummary: document.getElementById(
            "deviceListPaginationSummary",
        ),
        deviceListPaginationControls: document.getElementById(
            "deviceListPaginationControls",
        ),
        detailColumn: document.getElementById("detailColumn"),
        deviceSelectionEmptyState: document.getElementById(
            "deviceSelectionEmptyState",
        ),
        selectedDevicePanel: document.getElementById("selectedDevicePanel"),
        selectedDevicePreview: document.getElementById("selectedDevicePreview"),
        selectedDeviceTitle: document.getElementById("selectedDeviceTitle"),
        selectedDeviceMeta: document.getElementById("selectedDeviceMeta"),
        selectedDeviceBadge: document.getElementById("selectedDeviceBadge"),
        selectedDeviceEditBtn: document.getElementById("selectedDeviceEditBtn"),
        selectedDeviceFacts: document.getElementById("selectedDeviceFacts"),
        detailEmptyState: document.getElementById("detailEmptyState"),
        deviceDetail: document.getElementById("deviceDetail"),
        telemetryCount: document.getElementById("telemetryCount"),
        telemetryList: document.getElementById("telemetryList"),
        telemetryPager: document.getElementById("telemetry"),
        telemetryPagerSummary: document.getElementById("telemetrySummary"),
        telemetryPagerControls: document.getElementById("telemetryControls"),
        requestCardCount: document.getElementById("requestCardCount"),
        requestGrid: document.getElementById("requestGrid"),
        ncsEventSection: document.getElementById("ncsEventSection"),
        ncsEventCardCount: document.getElementById("ncsEventCardCount"),
        ncsEventGrid: document.getElementById("ncsEventGrid"),
        downlinkRequests: document.getElementById("downlinkRequests"),
        connectionTimeline: document.getElementById("connectionTimeline"),
        detailFiltersPanel: document.getElementById("detailFiltersPanel"),
        detailFilterFrom: document.getElementById("detailFilterFrom"),
        detailFilterTo: document.getElementById("detailFilterTo"),
        detailFilterType: document.getElementById("detailFilterType"),
        applyDetailFiltersBtn: document.getElementById("applyDetailFiltersBtn"),
        clearDetailFiltersBtn: document.getElementById("clearDetailFiltersBtn"),
        addDeviceBtn: document.getElementById("addDeviceBtn"),
        dashboardNotificationsDropdown: document.getElementById(
            "dashboardNotificationsDropdown",
        ),
        dashboardNotificationsBadge: document.getElementById(
            "dashboardNotificationsBadge",
        ),
        dashboardNotificationsSummary: document.getElementById(
            "dashboardNotificationsSummary",
        ),
        dashboardNotificationsList: document.getElementById(
            "dashboardNotificationsList",
        ),
        openDeviceSelectorBtn: document.getElementById("openDeviceSelectorBtn"),
        emptyStateSelectDeviceBtn: document.getElementById(
            "emptyStateSelectDeviceBtn",
        ),
        openAddDeviceFromSelectorBtn: document.getElementById(
            "openAddDeviceFromSelectorBtn",
        ),
        deviceActiveFilters: document.getElementById("deviceActiveFilters"),
        deviceModalLabel: document.getElementById("deviceModalLabel"),
        deviceForm: document.getElementById("deviceForm"),
        deviceFormError: document.getElementById("deviceFormError"),
        deviceImei: document.getElementById("deviceImei"),
        deviceTypeFilter: document.getElementById("deviceTypeFilter"),
        deviceLicenseFilter: document.getElementById("deviceLicenseFilter"),
        deviceCompanyFilter: document.getElementById("deviceCompanyFilter"),
        deviceSupplierFilter: document.getElementById("deviceSupplierFilter"),
        deviceModelFilter: document.getElementById("deviceModelFilter"),
        clearDeviceFiltersBtn: document.getElementById("clearDeviceFiltersBtn"),
        deviceSimNumberRoot: document.getElementById("deviceSimNumberRoot"),
        deviceDeviceIdRow: document.getElementById("deviceDeviceIdRow"),
        deviceDeviceId: document.getElementById("deviceDeviceId"),
        deviceDeviceIdLabel: document.getElementById("deviceDeviceIdLabel"),
        deviceDeviceIdHelp: document.getElementById("deviceDeviceIdHelp"),
        deviceGatewayLinksRow: document.getElementById("deviceGatewayLinksRow"),
        deviceGatewayLinksList: document.getElementById("deviceGatewayLinksList"),
        deviceGatewayLinksCount: document.getElementById("deviceGatewayLinksCount"),
        deviceGatewayLinksSelectAllBtn: document.getElementById("deviceGatewayLinksSelectAllBtn"),
        deviceGatewayLinksClearBtn: document.getElementById("deviceGatewayLinksClearBtn"),
        deviceGatewayLinksHelp: document.getElementById("deviceGatewayLinksHelp"),
        deviceDiaperSensitivityRow: document.getElementById("deviceDiaperSensitivityRow"),
        deviceDiaperSensitivityProfile: document.getElementById("deviceDiaperSensitivityProfile"),
        deviceDiaperSensitivityCustom: document.getElementById("deviceDiaperSensitivityCustom"),
        deviceDiaperPollutionRange: document.getElementById("deviceDiaperPollutionRange"),
        deviceDiaperPollutionValue: document.getElementById("deviceDiaperPollutionValue"),
        deviceDiaperSensitivityHelp: document.getElementById("deviceDiaperSensitivityHelp"),
        deviceTypeButtons: document.getElementById("deviceTypeButtons"),
        deviceLicenseId: document.getElementById("deviceLicenseId"),
        deviceLicenseSelect: document.getElementById("deviceLicenseSelect"),
        deviceCompany: document.getElementById("deviceCompany"),
        deviceCompanySelect: document.getElementById("deviceCompanySelect"),
        devicePreview: document.getElementById("devicePreview"),
        deviceSupplierButtons: document.getElementById("deviceSupplierButtons"),
        deviceModelButtons: document.getElementById("deviceModelButtons"),
        deviceConfigRoot: document.getElementById("deviceConfigRoot"),
        saveDeviceBtn: document.getElementById("saveDeviceBtn"),
        deviceImeiRow: document.getElementById("deviceImeiRow"),
        deviceSimRow: document.getElementById("deviceSimRow"),
        deviceConfigTabBtn: document.getElementById("deviceConfigTabBtn"),
        deviceConfigPane: document.getElementById("deviceConfigPane"),
        deviceGeneralTabBtn: document.getElementById("deviceGeneralTabBtn"),
        deviceGeneralPane: document.getElementById("deviceGeneralPane"),
        manageSettingsBtn: document.getElementById("manageSettingsBtn"),
        settingsSuppliersTabBtn: document.getElementById(
            "settingsSuppliersTabBtn",
        ),
        settingsModelsTabBtn: document.getElementById("settingsModelsTabBtn"),
        settingsCapabilitiesTabBtn: document.getElementById(
            "settingsCapabilitiesTabBtn",
        ),
        settingsApiUsersTabBtn: document.getElementById(
            "settingsApiUsersTabBtn",
        ),
        supplierListBody: document.getElementById("supplierListBody"),
        settingsSuppliersPagination:
            document.getElementById("settingsSuppliers"),
        settingsSuppliersPaginationSummary: document.getElementById(
            "settingsSuppliersSummary",
        ),
        settingsSuppliersPaginationControls: document.getElementById(
            "settingsSuppliersControls",
        ),
        modelForm: document.getElementById("modelForm"),
        modelPreview: document.getElementById("modelPreview"),
        modelSupplierButtons: document.getElementById("modelSupplierButtons"),
        modelInternalModel: document.getElementById("modelInternalModel"),
        modelCommercialName: document.getElementById("modelCommercialName"),
        modelDeviceTypeButtons: document.getElementById(
            "modelDeviceTypeButtons",
        ),
        modelImage: document.getElementById("modelImage"),
        modelPreviewContent: document.getElementById("modelPreviewContent"),
        modelListBody: document.getElementById("modelListBody"),
        modelsDeviceTypeButtons: document.getElementById(
            "modelsDeviceTypeButtons",
        ),
        modelsSupplierButtons: document.getElementById("modelsSupplierButtons"),
        modelsActiveFilters: document.getElementById("modelsActiveFilters"),
        modelsListLimit: document.getElementById("modelsListLimit"),
        modelsListSearch: document.getElementById("modelsListSearch"),
        clearModelsFiltersBtn: document.getElementById("clearModelsFiltersBtn"),
        settingsModelsPagination: document.getElementById("settingsModels"),
        settingsModelsPaginationSummary: document.getElementById(
            "settingsModelsSummary",
        ),
        settingsModelsPaginationControls: document.getElementById(
            "settingsModelsControls",
        ),
        resetModelBtn: document.getElementById("resetModelBtn"),
        deleteDeviceBtn: document.getElementById("deleteDeviceBtn"),
        saveModelBtn: document.getElementById("saveModelBtn"),
        modelTemplateSummary: document.getElementById("modelTemplateSummary"),
        modelsBreadcrumbModels: document.getElementById(
            "modelsBreadcrumbModels",
        ),
        modelsBreadcrumbNew: document.getElementById("modelsBreadcrumbNew"),
        modelsBreadcrumbCurrent: document.getElementById(
            "modelsBreadcrumbCurrent",
        ),
        modelsCarousel: document.getElementById("modelsCarousel"),
        modelsNewModelBtn: document.getElementById("modelsNewModelBtn"),
        modelDetailImage: document.getElementById("modelDetailImage"),
        modelDetailName: document.getElementById("modelDetailName"),
        modelDetailTitle: document.getElementById("modelDetailTitle"),
        modelDetailSupplier: document.getElementById("modelDetailSupplier"),
        modelDetailSupplierValue: document.getElementById(
            "modelDetailSupplierValue",
        ),
        modelDetailTypeValue: document.getElementById("modelDetailTypeValue"),
        modelDetailInternalModelValue: document.getElementById(
            "modelDetailInternalModelValue",
        ),
        modelDetailEditBtn: document.getElementById("modelDetailEditBtn"),
        modelDetailDeleteBtn: document.getElementById("modelDetailDeleteBtn"),
        capabilityTitle: document.getElementById("capabilityTitle"),
        capabilitySubtitle: document.getElementById("capabilitySubtitle"),
        capabilitySummary: document.getElementById("capabilitySummary"),
        saveCapabilitiesBtn: document.getElementById("saveCapabilitiesBtn"),
        capabilityGroups: document.getElementById("capabilityGroups"),
        capabilitySectionNav: document.getElementById("capabilitySectionNav"),
        capabilityDeviceTypeButtons: document.getElementById(
            "capabilityDeviceTypeButtons",
        ),
        capabilityCatalogEmpty: document.getElementById(
            "capabilityCatalogEmpty",
        ),
        capabilityCatalogViewer: document.getElementById(
            "capabilityCatalogViewer",
        ),
        capabilitySupplierButtons: document.getElementById(
            "capabilitySupplierButtons",
        ),
        capabilitySupplierSummary: document.getElementById(
            "capabilitySupplierSummary",
        ),
        capabilitySupplierClear: document.getElementById(
            "capabilitySupplierClear",
        ),
        discoveryModelSummary: document.getElementById("discoveryModelSummary"),
        discoveryDeviceSelect: document.getElementById("discoveryDeviceSelect"),
        discoveryRefreshDevicesBtn: document.getElementById(
            "discoveryRefreshDevicesBtn",
        ),
        discoveryGenerateBtn: document.getElementById("discoveryGenerateBtn"),
        discoveryApplyBtn: document.getElementById("discoveryApplyBtn"),
        discoveryStatus: document.getElementById("discoveryStatus"),
        discoveryEvidence: document.getElementById("discoveryEvidence"),
        apiUserForm: document.getElementById("apiUserForm"),
        apiUserId: document.getElementById("apiUserId"),
        apiUsername: document.getElementById("apiUsername"),
        apiUserPassword: document.getElementById("apiUserPassword"),
        apiUserRole: document.getElementById("apiUserRole"),
        apiUserLicenseRefId: document.getElementById("apiUserLicenseRefId"),
        apiUserEnabled: document.getElementById("apiUserEnabled"),
        resetApiUserBtn: document.getElementById("resetApiUserBtn"),
        saveApiUserBtn: document.getElementById("saveApiUserBtn"),
        apiUserListBody: document.getElementById("apiUserListBody"),
        settingsApiUsersPagination: document.getElementById("settingsApiUsers"),
        settingsApiUsersPaginationSummary: document.getElementById(
            "settingsApiUsersSummary",
        ),
        settingsApiUsersPaginationControls: document.getElementById(
            "settingsApiUsersControls",
        ),
        settingsCompanyTabBtn: document.getElementById("settingsCompanyTabBtn"),
        companyForm: document.getElementById("companyForm"),
        companyId: document.getElementById("companyId"),
        companyName: document.getElementById("companyName"),
        resetCompanyBtn: document.getElementById("resetCompanyBtn"),
        saveCompanyBtn: document.getElementById("saveCompanyBtn"),
        companyListBody: document.getElementById("companyListBody"),
        licenseForm: document.getElementById("licenseForm"),
        licenseId: document.getElementById("licenseId"),
        licenseCompanySelect: document.getElementById("licenseCompanySelect"),
        licenseLicenseId: document.getElementById("licenseLicenseId"),
        licenseName: document.getElementById("licenseName"),
        resetLicenseBtn: document.getElementById("resetLicenseBtn"),
        saveLicenseBtn: document.getElementById("saveLicenseBtn"),
        licenseListBody: document.getElementById("licenseListBody"),
        settingsCompanyPagination: document.getElementById("settingsCompany"),
        settingsCompanyPaginationSummary: document.getElementById(
            "settingsCompanySummary",
        ),
        settingsCompanyPaginationControls: document.getElementById(
            "settingsCompanyControls",
        ),
        settingsLicensesPagination: document.getElementById("settingsLicenses"),
        settingsLicensesPaginationSummary: document.getElementById(
            "settingsLicensesSummary",
        ),
        settingsLicensesPaginationControls: document.getElementById(
            "settingsLicensesControls",
        ),
    };
}
