persistence true
persistence_location /mosquitto/data/
log_dest stdout
allow_anonymous false

listener 1883 0.0.0.0
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl

listener 8883 0.0.0.0
cafile /mosquitto/config/certs/fullchain.pem
certfile /mosquitto/config/certs/fullchain.pem
keyfile /mosquitto/config/certs/privkey.pem
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl
